import Head from "next/head";
import Image from "next/image";
import HomeBalconyProduct from "../components/Home/HomeBalconyProduct";
import HomeDoorProduct from "../components/Home/HomeDoorProduct";
import HomeProduct from "../components/Home/HomeProduct";
import HomeTop from "../components/Home/HomeTop";
import HowItWorks from "../components/Home/HowItWorks";
import { useGetListProducts } from "../services/datasource";
import ProductListing from "../components/Home/ProductListing";
import HomeProductChair from "../components/Home/HomeProductChair";
import HomeProdcutBed from "../components/Home/HomeProdcutBed";

export default function Home({ productList }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeTop />
      <ProductListing />
      <HomeProductChair productData={productList} />
      <HomeProdcutBed productData={productList} />
      {/* <HomeProduct productData={productList} /> */}
      {/* <HomeDoorProduct productData={productList} /> */}
      {/* <HomeBalconyProduct productData={productList} /> */}
    </div>
  );
}

export async function getServerSideProps() {
  const data = await useGetListProducts();

  return {
    props: {
      productList: data?.data?.getProduct,
    },
  };
}
