import Head from "next/head";
import Image from "next/image";
import HomeProduct from "../components/Home/HomeProduct";
import HomeTop from "../components/Home/HomeTop";
import HowItWorks from "../components/Home/HowItWorks";
import { useGetListProducts } from "../services/datasource";

export default function Home({ productList }) {
  // console.log(productList);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeTop />
      <div className="mt-16">
        <h1 className="font-lato font-semibold md:text-4xl text-xl text-center">
          My Products
        </h1>
        <HomeProduct productData={productList} />
      </div>
      {/* <HowItWorks /> */}
    </div>
  );
}

export async function getServerSideProps() {
  const data = await useGetListProducts();

  // console.log(data?.data?.getProduct);

  return {
    props: {
      productList: data?.data?.getProduct,
    },
  };
}
